# Generated by Django 5.2.4 on 2025-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
                ('description', models.TextField()),
                ('priority', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
